# Configuração do Servidor
server:
  port: 8080

# Configuração do Banco H2 (em memória)
spring:
  datasource:
    url: jdbc:h2:mem:clickfarma
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # Configuração do JPA (Hibernate)
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Console do H2
  h2:
    console:
      enabled: true
      path: /h2-console

# Configuração do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true

# Configuração de logging para debug
logging:
  level:
    org.springframework.security: DEBUG
    com.clickfarma.clickfarma_backend: DEBUG